# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-02 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.CharField(max_length=100, verbose_name='OID')),
                ('objectType', models.CharField(max_length=200, verbose_name='Tipo')),
            ],
            options={
                'ordering': ['objectType'],
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
            },
        ),
    ]
